spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://elite-sql:5432/Orders}
    username: ${DB_USERNAME:pg_admin}
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TOKEN_ISSUER_URI:http://localhost:8181}/realms/elite