spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Orders
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect