server:
  port: 8083

spring:
  application:
    name: INVENTORY-SERVICE
  profiles:
    active: ${ACTIVE_PROFILE:dev}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
