spring:
  data:
    mongodb:
      username: user
      password: password
      port: 27017
      database: Products
      authentication-database: admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/elite